### PR TITLE
Bug 2004924: Update dependencies to K8s 1.22

### PR DESCRIPTION
**Pull request by JoelSpeed**
This resolves an issue where the cloud-provider wouldn't attach the master machine to a service backend, see the original bug for further details

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/hold

This must merge after https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/128

**Review by Fedosin — APPROVED** [review]
/approve
/lgtm

**Comment by JoelSpeed** [comment]
/hold cancel

Dependent PR has now merged, this can go once we get a staff engineer approval

**Comment by hardys** [comment]
[patch-manager] https://bugzilla.redhat.com/show_bug.cgi?id=2004924 identified as blocker issue, added staff-eng-approved

**Comment by cuppett** [comment]
@hardys I think this still needs the "approved" label?

**Pull request merged**
