### PR TITLE
OCPCLOUD-2725: Reintroduce rebase to K8s 1.31

### PR DESCRIPTION
**Pull request by JoelSpeed**
This reverts #95 while adding an additional commit to fix the HyperShift issue we observed

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/payload-job periodic-ci-openshift-hypershift-release-4.18-periodics-e2e-aws-ovn-conformance

**Comment by elmiko** [comment]
change lgtm, but looks like the images job got oom killed, we might need to bump it up

/test images

**Comment by JoelSpeed** [comment]
[HyperShift job](https://github.com/openshift/cloud-provider-aws/pull/97#issuecomment-2371709363) is green this time
/approve

**Pull request merged**
