### PR TITLE
OCPBUGS-14696: Merge https://github.com/kubernetes/cloud-provider-aws:master (cab0100) into master

### PR DESCRIPTION
**Pull request by JoelSpeed**
Reverts openshift/cloud-provider-aws#43

The rebase was reverted, this PR un-reverts the rebase so that we can re-inroduce the changes from the rebase. Will be building images off of this to explore the disruption data that was found.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade

**Comment by JoelSpeed** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-sdn-upgrade periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade

**Comment by JoelSpeed** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade

Have added a commit to switch the health checks over, which I believe should resolve the issue we have been seeing. Need multiple runs to validate that it does solve the issue

**Comment by JoelSpeed** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade 10

**Comment by JoelSpeed** [comment]
/approve

Based on test results we've seen here, the additional patch that I've added has resolved the disruption issues we've seen that cause this PR to be reverted originally. Have started the process of getting the patch in upstream, will bring any updates from that PR back in post merge if required.

**Comment by elmiko** [comment]
the carry patch makes sense to me, we just need to be careful about the 1.28 rebase in case upstream decides to change something, but i don't think that's a big risk.

/lgtm

**Pull request merged**
