### PR TITLE
OCPBUGS-21839: Upgrade x/net to v0.17.0

### PR DESCRIPTION
**Pull request by nrb**

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Is this fixed upstream? Can we get the relevant upstream fix linked within the commit message as we normally do? `UPSTREAM: ####: ` style

**Comment by damdo** [comment]
Looks like it is, here: https://github.com/kubernetes/cloud-provider-aws/pull/675

**Review by damdo — COMMENTED** [review]
/lgtm

**Pull request merged**
