### PR TITLE
OCPBUGS-8213: Ensure removal of security group rules on deleting load balancers

### PR DESCRIPTION
**Pull request by JoelSpeed**
When the security group that an instance belongs to is not tagged with the cluster tag, the CCM will happily add a rule from the instance security group to allow traffic from the load balancer security group. However, when it comes to removing the load balancer, if it is intending to remove the security group, it currently does not take into account unmanaged groups where it must still remove the rules to allow the security group to be removed.

More details in the upstream PR and linked issue.

### CODE REVIEW

**Comment by candita** [comment]
@JoelSpeed - will this merge any time soon?

**Comment by JoelSpeed** [comment]
Still not getting any response upstream about the fix, will discuss with the team about merging it in the absence of upstream attention

**Comment by elmiko** [comment]
just commenting here, i'm happy to bring this up with the sig again, but i feel that @JoelSpeed has done the due diligence on this patch and i would be comfortable carrying it. hopefully we can get upstream to accept it at some point.

**Comment by JoelSpeed** [comment]
Manually adding the jira labels since the bug report is restricted and not public
@elmiko are you comfortable to tag the approve/lgtm?

**Review by elmiko — COMMENTED** [review]
this is complex stuff, thanks for the fix @JoelSpeed 

/approve
/lgtm

**Pull request merged**
